paths:
  /api/products/mockingproducts:
    get:
      summary: Genera productos de prueba
      tags:
        - Productos
      description: Genera una lista de productos de prueba para testing
      responses:
        '200':
          description: Productos de prueba generados
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /api/products/loggerTest:
    get:
      summary: Prueba de logger
      tags:
        - Productos
      description: Realiza una prueba del sistema de logging
      responses:
        '200':
          description: Prueba de logger exitosa

  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Productos
      description: Obtiene una lista de todos los productos disponibles
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      security:
        - bearerAuth: []
      summary: Crea un nuevo producto
      tags:
        - Productos
      description: Crea un nuevo producto en el sistema. Requiere autorización de administrador
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          descripion: Producto creado exitosamente
          content:
            applicattion/json:
              schema:
                $ref: '#/components/schemas/Product'
        '403':
          description: Solo los administradores pueden crear productos

  /api/products/{pid}:
    get:
      summary: Obtiene un producto por ID
      tags:
        - Productos
      description: Obtiene los detalles de un producto específico por su ID
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado

    put:
      security:
        - bearerAuth: []
      summary: Actualiza un producto por ID
      tags:
        - Productos
      description: Actualiza los detalles de un producto específico. Requiere autorización de administrador
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Producto actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '403':
          description: Solo los administradores pueden actualizar productos
        '404':
          description: Producto no encontrado

    delete:
      security:
        - bearerAuth: []
      summary: Elimina un producto por ID
      tags:
        - Productos
      description: Elimina un producto específico del sistema. Requiere autorización de administrador
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        '200':
          description: Producto eliminado exitosamente
        '403':
          description: Solo los administradores pueden eliminar productos
        '404':
          description: Producto no encontrado